export const CONFIG = Object.freeze({
  FONT: Object.freeze({
    NAME: "Open Sans",
    FILE: "OpenSans_SemiCondensed-Medium.ttf",
    URL: "./OpenSans_SemiCondensed-Medium.ttf",
  }),
  CODE_FONT: Object.freeze({
    NAME: "JetBrains Mono",
    FILE: "JetBrainsMono-Medium.ttf",
    URL: "./JetBrainsMono-Medium.ttf",
  }),
  PDF: Object.freeze({
    WORKER_SRC:
      "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js",
    SCALE: 1.5,
    RENDER_SCALE: 2.0,
    IMAGE_FORMAT: "image/jpeg",
    IMAGE_QUALITY: 0.92,
    RENDER_BATCH_SIZE: 10,
    RENDER_INTENT: "print",
  }),
  OVERLAY: Object.freeze({
    MIN_HEIGHT: 25,
    MIN_FONT_SIZE: 4,
    MAX_FONT_SIZE: 150,
    VERTICAL_THRESHOLD: 2.0,
    OVERFLOW_TOLERANCE: 0.5,
    FONT_SIZE_GUESS_MULTIPLIER: 1.8,
    FONT_SIZE_UPSCALE_MULTIPLIER: 1.5,
    BINARY_SEARCH_ITERATIONS: 10,
    BINARY_SEARCH_PRECISION: 0.5,
  }),
  MERGE: Object.freeze({
    TOLERANCE_HORIZONTAL: 10,
    TOLERANCE_VERTICAL_MULTIPLIER: 0.5,
    MIN_GAP: -2,
  }),
  CACHE: Object.freeze({
    MAX_FONT_SIZE_CACHE: 500,
    MAX_TABLE_LAYOUT_CACHE: 500,
    MAX_PAGE_CACHE: 100,
  }),
  RENDER: Object.freeze({
    INTERSECTION_ROOT_MARGIN: "500px 0px",
    INTERSECTION_THRESHOLD: 0,
    BATCH_DELAY: 0,
    QUEUE_SORT_WINDOW_CENTER: 2,
  }),
  TABLE: Object.freeze({
    CELL_PADDING: 4,
    BORDER_WIDTH: 1,
    LINE_HEIGHT: 1.25,
    HEADER_BOOST: 1.15,
    MIN_COL_PERCENT: 8,
    MAX_COL_PERCENT: 60,
    COL_DIVISOR: 2.5,
    MAX_ITERATIONS: 15,
    SCALE_FACTOR: 1.1,
    REDUCE_FACTOR: 0.9,
    HEADROOM_THRESHOLD: 0.6,
    UTILIZATION_THRESHOLD: 0.6,
    REDISTRIBUTION_FACTOR: 0.5,
    MAX_SCALE_HEADER: 2.0,
    MAX_SCALE_DATA: 2.5,
    MIN_SCALE: 1.0,
    SCALE_ADJUSTMENT: 0.97,
    WRAP_WIDTH_FACTOR: 0.9,
  }),
  PDF_RENDERER: Object.freeze({
    BASELINE_RATIO_DEFAULT: 0.78,
    LIST_BULLET_INDENT: 0.5,
    LIST_CONTINUATION_INDENT: 0.3,
    LIST_LINE_HEIGHT: 1.3,
    LIST_ITEM_SPACING: 0.4,
    CODE_LINE_HEIGHT: 1.4,
    CODE_PADDING: 8,
    CODE_CONTINUATION_INDENT: "    ",
    TABLE_HEADER_OPACITY: 0.15,
    TABLE_ROW_EVEN_OPACITY: 0.08,
    TABLE_ROW_ODD_OPACITY: 0.05,
  }),
  EXPORT: Object.freeze({
    HTML_IMAGE_FORMAT: "image/webp",
    HTML_IMAGE_QUALITY: 0.85,
    BATCH_SIZE: 10,
    BATCH_PROGRESS_INTERVAL: 30,
    PDF_BATCH_SIZE: 5,
    PDF_SAVE_DELAY: 300,
    FILENAME_PADDING: 3,
  }),
  UI: Object.freeze({
    DEBOUNCE_DELAY: 300,
    DEBOUNCE_SLIDER: 150,
    DEBOUNCE_TEXT: 500,
    COORD_APPLY_DELAY: 300,
    SAVING_INDICATOR_HIDE_DELAY: 200,
    RENDER_ANIMATION_FRAME_DELAY: 0,
  }),
  COORDINATES: Object.freeze({
    LETTERS: ["T", "L", "B", "R"],
    MAP: Object.freeze({ T: 0, L: 1, B: 2, R: 3 }),
    DEFAULT_ORDER: "TLBR",
    ORDERINGS: Object.freeze(
      ["TLBR", "LTRB", "LBRT", "BLTR", "TRBL", "TBRL"].map((order) =>
        Object.freeze({
          order,
          name: order.split("").join("-"),
        })
      )
    ),
  }),
  CONTENT_TYPES: Object.freeze({
    TEXT: "text",
    CODE: "code",
    LIST: "list",
    TABLE: "table",
    IMAGE: "image",
  }),
  COLOR_PALETTES: Object.freeze({
    cream: Object.freeze([[254, 250, 234], [60, 50, 40], [230, 220, 200], 97]),
    sepia: Object.freeze([[244, 237, 219], [74, 59, 44], [220, 210, 190], 96]),
    mint: Object.freeze([[240, 248, 240], [45, 65, 55], [215, 230, 215], 95]),
    darkOlive: Object.freeze([[42, 48, 42], [230, 235, 220], [60, 70, 60], 98]),
    charcoal: Object.freeze([[40, 44, 52], [230, 237, 243], [60, 68, 78], 99]),
    highContrast: Object.freeze([
      [235, 235, 235],
      [0, 0, 0],
      [60, 60, 60],
      100,
    ]),
    code: Object.freeze([[40, 44, 52], [171, 178, 191], [60, 68, 78], 98]),
    dyslexia: Object.freeze([
      [255, 253, 208],
      [20, 20, 20],
      [240, 235, 180],
      98,
    ]),
  }),
  DEFAULT_PALETTE: "cream",
  REGEX: Object.freeze({
    PYTHON: /^(import|from|def|class|async def|@\w+)/m,
    PYTHON_COLON: /:\s*$/m,
    TYPESCRIPT: /interface\s+\w+|:\s*(string|number|boolean)/m,
    JAVASCRIPT: /^(import|export|const|let|var|function|class)\s/m,
    HTML: /<(!DOCTYPE|html|head|body|div)/i,
    CSS: /^[.#@]?[\w-]+\s*{/m,
    JSON_START: /^\s*[{\[]/,
    LIST_BULLET: /^[•\-*]\s/,
    NEWLINE: /\r?\n/,
    BR_TAG: /<br\s*\/?>/gi,
  }),
  VALIDATION: Object.freeze({
    MIN_PAGE: 1,
    MAX_EXPAND_AMOUNT: 100,
    MIN_EXPAND_AMOUNT: 1,
    EXPAND_WARNING_THRESHOLD: 100,
  }),
  MESSAGES: Object.freeze({
    NO_FILE: "No file selected",
    NO_PDF: "No PDF",
    USING_DEFAULT: "Using default",
    LOADING_PDF: "Loading PDF...",
    SELECT_PDF: "Select a PDF file to begin",
    INVALID_COORDINATE:
      "Invalid coordinate order: must contain T, L, B, R exactly once",
    FONT_LOAD_ERROR: "Could not load font. PDF will use default font.",
    PDF_LOAD_ERROR: "Error loading PDF",
    OPERATION_IN_PROGRESS: "Please wait for the current operation to complete.",
    DELETE_CONFIRM: "Delete this overlay?",
    JSON_MISMATCH_WARNING:
      "You are loading new overlay data for the current PDF.\n\nMake sure this JSON matches your loaded PDF.\n\nContinue?",
    EXPAND_LARGE_WARNING:
      "Expand by {amount}px? This is quite large and may cause overlaps.",
    SPLIT_ALL_CONFIRM:
      "Split {total} pages into individual files?\n\nThis will download {total} separate PDFs.\n\nContinue?",
    SPLIT_BY_FILES_CONFIRM:
      "Split {total} pages into {numFiles} files?\n\nEach file will contain ~{pagesPerFile} pages.\n\nContinue?",
    SPLIT_BY_PAGES_CONFIRM:
      "Split into groups of {pagesPerFile} pages?\n\nThis will create {numFiles} files.\n\nContinue?",
    EXPORT_PAGES_CONFIRM:
      "Export {count} specific pages?\n\nPages: {list}\n\nContinue?",
    APPLY_ALL_CONFIRM: 'Apply "{order}" to ALL pages?',
    INVALID_PAGE_SPEC:
      'Invalid page specification.\n\nExamples:\n• "1,5,10"\n• "1-5,10,15-20"',
    INVALID_EXPAND_AMOUNT: "Please enter a valid positive number",
    RANGE_ERROR_POSITIVE: "Page numbers must be positive",
    RANGE_ERROR_ORDER: "Start page must be ≤ end page",
    RANGE_ERROR_EXCEEDS: "End page exceeds total pages ({max})",
  }),
  KEYBOARD_SHORTCUTS: Object.freeze({
    SPLIT: "S",
    EXPORT_PDF: "E",
    PRINT: "P",
    EXPORT_HTML: "H",
  }),
});
